#include $(srctree)/drivers/misc/mediatek/imgsensor/src/Makefile.custom

obj-y += ov13856mipiraw_Sensor.o
#[linyimin start] Remove sensor's otp cali
#obj-y += ov13856_otp_cal.o
#[linyimin end]
obj-y += ov13856_pdaf_cal.o
