#include $(srctree)/drivers/misc/mediatek/imgsensor/src/Makefile.custom

obj-y += ov13855mipiraw_Sensor.o
#[linyimin start] Remove sensor's otp cali
#obj-y += ov13855_otp_cal.o
#[linyimin end]
obj-y += ov13855_pdaf_cal.o
